# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Entry.create!(word: "absolute music", definition: "instrumental music not intended to represent or illustrate something else.")
Entry.create!(word: "a cappella", definition: "(with reference to choral music) sung without instrumental accompaniment")
Entry.create!(word: "acciaccatura", definition: "a grace note performed as quickly as possible before an essential note of a melody.")
Entry.create!(word: "accompaniment", definition: "a musical part which supports or partners an instrument, voice, or group")
Entry.create!(word: "accompanist", definition: "a person who provides a musical accompaniment to another musician or to a singer.")
Entry.create!(word: "account", definition: "a report or description of an event or experience")
Entry.create!(word: "aeolian mode", definition: "the mode represented by the natural diatonic scale A–A (containing a minor 3rd, 6th, and 7th).")
Entry.create!(word: "aerophone", definition: "a wind instrument.")
Entry.create!(word: "afrofuturism", definition: "a movement in literature, music, art, etc., featuring futuristic or science fiction themes which incorporate elements of black history and culture")
Entry.create!(word: "agogic", definition: "relating to or denoting accentuation within musical phrases by slight lengthening of notes.")
Entry.create!(word: "alap", definition: "(in Indian music) the improvised section of a raga, forming a prologue to the formal expression.")
Entry.create!(word: "aleatory", definition: "depending on the throw of a dice or on chance; random.")
Entry.create!(word: "alla breve", definition: "a time signature indicating two or four minim beats in a bar.")
Entry.create!(word: "allemande", definition: "any of a number of German dances, in particular an elaborate court dance popular in the 16th century.")
Entry.create!(word: "altissimo", definition: "very high in pitch")
Entry.create!(word: "alto", definition: "(especially in church music) the highest adult male singing voice (sometimes distinguished from the countertenor voice as using falsetto).")
Entry.create!(word: "alto clef", definition: "a clef placing middle C on the middle line of the stave, used chiefly for viola music.")
Entry.create!(word: "altoist", definition: "a person who plays an alto instrument, in particular a saxophone.")
Entry.create!(word: "amati", definition: "a family of Italian violin-makers from Cremona. In the 16th and 17th centuries three generations of the Amatis developed the basic proportions of the violin, viola, and cello.")
Entry.create!(word: "anderson, marian", definition: "(1897–1993), American operatic contralto. In 1955 she became the first black singer to perform at the New York Metropolitan Opera.")
Entry.create!(word: "anglican chant", definition: "a method of singing unmetrical psalms and canticles to short harmonized melodies, the first note being extended to accommodate as many syllables as necessary.")
Entry.create!(word: "anthemic", definition: "(of a song) like an anthem in being rousing or uplifting")
Entry.create!(word: "anticipation", definition: "the action of anticipating something; expectation or prediction")
Entry.create!(word: "antiphonal", definition: "(of music, especially church music, or a section of a church liturgy) sung, recited, or played alternately by two groups.")
Entry.create!(word: "antiphonary", definition: "(in the Western Christian Church) a book of plainsong for the Divine Office.")
Entry.create!(word: "antiphony", definition: "antiphonal singing, playing, or chanting.")
Entry.create!(word: "appoggiatura", definition: "a grace note which delays the next note of the melody, taking half or more of its written time value.")
Entry.create!(word: "aria", definition: "a long accompanied song for a solo voice, typically one in an opera or oratorio.")
Entry.create!(word: "arioso", definition: "(especially in opera and oratorio) vocal music that is more melodic than recitative but less formal than an aria")
Entry.create!(word: "arpeggiate", definition: "play (a chord) as a series of ascending or descending notes")
Entry.create!(word: "arpeggio", definition: "the notes of a chord played in rapid succession, either ascending or descending.")
Entry.create!(word: "arr.", definition: "(of a piece of music) arranged by")
Entry.create!(word: "arranger", definition: "a person who adapts a musical composition for performance")
Entry.create!(word: "ashkenazy, vladimir", definition: "(born 1937), Russian-born pianist; full name Vladimir Davidovich Ashkenazy. A child prodigy, he left the Soviet Union in 1963, finally settling in Iceland in 1973.")
Entry.create!(word: "athematic", definition: "(of a composition) not based on the use of themes.")
Entry.create!(word: "atonal", definition: "not written in any key or mode")
Entry.create!(word: "attune", definition: "make receptive or aware")
Entry.create!(word: "aubade", definition: "a poem or piece of music appropriate to the dawn or early morning.")
Entry.create!(word: "augmentation", definition: "the action or process of making or becoming greater in size or amount")
Entry.create!(word: "autotune", definition: "a device or facility for tuning something automatically, especially a computer program which enables the correction of an out-of-tune vocal performance.")
Entry.create!(word: "back catalogue", definition: "all the works previously produced by a recording artist or record company")
Entry.create!(word: "background music", definition: "music intended as an unobtrusive accompaniment to an activity or to provide atmosphere in a film.")
Entry.create!(word: "baker, dame janet", definition: "(born 1933), English operatic mezzo-soprano; full name Dame Janet Abbott Baker.")
Entry.create!(word: "ballad", definition: "a poem or song narrating a story in short stanzas. Traditional ballads are typically of unknown authorship, having been passed on orally from one generation to the next.")
Entry.create!(word: "balladeer", definition: "a singer or composer of ballads.")
Entry.create!(word: "ballad-monger", definition: "a composer or seller of ballads")
Entry.create!(word: "ballad opera", definition: "a theatrical entertainment popular in early 18th-century England, taking the form of a satirical play interspersed with traditional or operatic songs. The best-known example is John Gay's \"The Beggar's Opera\" (1728).")
Entry.create!(word: "bandleader", definition: "a player at the head of a musical band.")
Entry.create!(word: "bandmaster", definition: "the conductor of a musical band, especially a brass or military one.")
Entry.create!(word: "bandsman", definition: "a player in a musical band, especially a military or brass one.")
Entry.create!(word: "barcarole", definition: "a song traditionally sung by Venetian gondoliers.")
Entry.create!(word: "baritone", definition: "an adult male singing voice between tenor and bass")
Entry.create!(word: "baritonist", definition: "a person who plays a baritone instrument, in particular a saxophone or a horn.")
Entry.create!(word: "bar line", definition: "a vertical line used in a musical score to mark a division between bars.")
Entry.create!(word: "baroque", definition: "relating to or denoting a style of European architecture, music, and art of the 17th and 18th centuries that followed Mannerism and is characterized by ornate detail. In architecture the period is exemplified by the palace of Versailles and by the work of Wren in England. Major composers include Vivaldi, Bach, and Handel; Caravaggio and Rubens are important baroque artists.")
Entry.create!(word: "barré", definition: "a method of playing a chord on the guitar or a similar instrument in which one finger is laid across all the strings at a particular fret.")
Entry.create!(word: "bass", definition: "the lowest adult male singing voice")
Entry.create!(word: "bass clef", definition: "a clef placing F below middle C on the second-highest line of the stave.")
Entry.create!(word: "bassist", definition: "a person who plays a double bass or bass guitar.")
Entry.create!(word: "bassline", definition: "the lowest part or sequence of notes in a piece of music.")
Entry.create!(word: "bass note", definition: "a low note played on a musical instrument or sung by a singer")
Entry.create!(word: "basso", definition: "a bass voice or vocal part.")
Entry.create!(word: "basso profundo", definition: "a bass singer with an exceptionally low range.")
Entry.create!(word: "baton", definition: "a thin stick used by a conductor to direct an orchestra or choir.")
Entry.create!(word: "beat time", definition: "indicate or follow a musical tempo with a baton or other means.")
Entry.create!(word: "bel canto", definition: "a lyrical style of operatic singing using a full, rich, broad tone and smooth phrasing")
Entry.create!(word: "bellows", definition: "a device with an air bag that emits a stream of air when squeezed together with two handles, used for blowing air into a fire")
Entry.create!(word: "berceuse", definition: "a lullaby.")
Entry.create!(word: "berlin, irving", definition: "(1888–1989), Russian-born American songwriter; born Israel Baline. Notable works: the songs ‘God Bless America’ (1918) and ‘White Christmas’ (1942) and the score for "Annie Get Your Gun" (stage, 1946; film, 1950).")
Entry.create!(word: "bis", definition: "(as a direction) again.")
Entry.create!(word: "bitonal", definition: "(of music) having parts in two different keys sounding together.")
